name: 清理者
on:
    schedule:
        - cron: "0 * * * *"
    workflow_dispatch:
jobs:
    cleaner:
        runs-on: ubuntu-latest
        steps:
            - name: Harden the runner (Audit all outbound calls)
              uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
              with:
                egress-policy: audit

            - name: 签出
              uses: actions/checkout@900f2210b1d28bbbd0bd22d17926b9e224e8f231 # main
            - name: 准备 pnpm
              uses: pnpm/action-setup@3e835812ef01165f4f8ae08ade56da44427ed4e0 # master
              with:
                  version: latest
            - name: 准备 node.js
              uses: actions/setup-node@670825a89dc0abd596e7a3abd0f5e3f6e5faf37c # main
              with:
                  node-version: 24
                  cache: pnpm
            - name: 安装 pnpm 依赖
              run: pnpm install
            - name: 准备 Tailscale
              uses: tailscale/github-action@586e48b2b708c2650a83e9e6981a832a59e1119d # main
              with:
                  oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
                  oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
                  tags: tag:ci
                  version: latest
            - name: 运行清理者
              env:
                  MOEGIRL_ZH_BOTUSERNAME: ${{ vars.MOEGIRL_ZH_BOTUSERNAME }}
                  MOEGIRL_ZH_BOTPASSWORD: ${{ secrets.MOEGIRL_ZH_BOTPASSWORD }}
                  MOEGIRL_MZH_BOTUSERNAME: ${{ vars.MOEGIRL_MZH_BOTUSERNAME }}
                  MOEGIRL_MZH_BOTPASSWORD: ${{ secrets.MOEGIRL_MZH_BOTPASSWORD }}
                  MOEGIRL_MOEGIRLSSOUSERID: ${{ vars.MOEGIRL_MOEGIRLSSOUSERID }}
                  MOEGIRL_MOEGIRLSSOTOKEN: ${{ secrets.MOEGIRL_MOEGIRLSSOTOKEN }}
                  OTEL_TRACES_EXPORTER: ${{ vars.OTEL_TRACES_EXPORTER }}
                  OTEL_EXPORTER_OTLP_ENDPOINT: ${{ vars.OTEL_EXPORTER_OTLP_ENDPOINT }}
                  OTEL_EXPORTER_OTLP_INSECURE: ${{ vars.OTEL_EXPORTER_OTLP_INSECURE }}
                  OTEL_NODE_RESOURCE_DETECTORS: ${{ vars.OTEL_NODE_RESOURCE_DETECTORS }}
                  OTEL_SERVICE_NAME: ${{ vars.OTEL_SERVICE_NAME }}
              run: node -r ./logger.js 清理者
